name: Build and Upload SQL-Cleaner

on:
  push:
    paths:
      - 'sql_cleaner/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install UPX on Windows
        if: runner.os == 'Windows'
        run: choco install upx
        shell: powershell

      - name: Build
        run: cargo build --release
        working-directory: ./sql_cleaner

      - name: Compress exe with UPX
        if: runner.os == 'Windows'
        run: upx --best --lzma sql_cleaner/target/release/SQL-Cleaner.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: SQL-Cleaner-${{ runner.os }}
          path: |
            ${{ runner.os != 'Windows' && 'sql_cleaner/target/release/SQL-Cleaner' || '' }}
            ${{ runner.os == 'Windows' && 'sql_cleaner/target/release/SQL-Cleaner.exe' || '' }}
